version: 2.1

orbs:
  maven: circleci/maven@0.0.12

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
    store_artifacts:
      path: rr-pet-clinic-app/target/rr-pet-clinic-app-0.0.1-SNAPSHOT.jar
