spring:
  datasource:
    url: jdbc:mysql://localhost:3307/petclinic_prod
    username: petclinic_prod_user
    password: prod
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false
